#!/usr/bin/env bash
set -euo pipefail
# Description: Jalankan development Expo Mobile manual + embed cert.pem dari hasil run.dev.ssl.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
ENV_FILE="$ROOT_DIR/.env"
MOBILE_APP_DIR="$ROOT_DIR/core-clients/app-client/apps/mobile"
WORKSPACE_DIR="$ROOT_DIR/core-clients/app-client"

if [[ ! -d "$MOBILE_APP_DIR" ]]; then
  echo "[ERROR] Mobile app directory tidak ditemukan: $MOBILE_APP_DIR" >&2
  exit 1
fi

if ! command -v pnpm >/dev/null 2>&1; then
  echo "[ERROR] pnpm tidak ditemukan. Install pnpm terlebih dahulu." >&2
  exit 1
fi

if [[ -f "$ENV_FILE" ]]; then
  set -a
  . "$ENV_FILE"
  set +a
fi

SAFE_APP_NAME="${SERVICE_SERVER_NAME:-${SERVICE_SERVER_DOMAIN:-myapp}}"
SAFE_APP_NAME="${SAFE_APP_NAME// /-}"
SAFE_APP_NAME="${SAFE_APP_NAME,,}"

CERT_SOURCE=""
FALLBACK_CERT="$ROOT_DIR/gen-${SAFE_APP_NAME}.crt"
if [[ -r "$FALLBACK_CERT" ]]; then
  CERT_SOURCE="$FALLBACK_CERT"
elif [[ -n "${SSL_CERT_PATH:-}" && -r "${SSL_CERT_PATH}" ]]; then
  CERT_SOURCE="${SSL_CERT_PATH}"
fi

ROOT_CA_SOURCE="$ROOT_DIR/step-ca-public-root.pem"
TARGET_CERT_DIR="$MOBILE_APP_DIR/certs"
TARGET_CERT_FILE="$TARGET_CERT_DIR/cert.pem"
TARGET_ROOT_CA_FILE="$TARGET_CERT_DIR/root-ca.pem"
MOBILE_ENV_FILE="$MOBILE_APP_DIR/.env.local"

mkdir -p "$TARGET_CERT_DIR"

if [[ -n "$CERT_SOURCE" && -r "$CERT_SOURCE" ]]; then
  cp "$CERT_SOURCE" "$TARGET_CERT_FILE"
  echo "[OK] Embedded certificate: $TARGET_CERT_FILE"
else
  echo "[WARN] Sertifikat tidak ditemukan / tidak bisa dibaca. Jalankan './run.sh run.dev.ssl.sh' dulu bila perlu HTTPS lokal."
fi

if [[ -f "$ROOT_CA_SOURCE" ]]; then
  cp "$ROOT_CA_SOURCE" "$TARGET_ROOT_CA_FILE"
  echo "[OK] Embedded root CA: $TARGET_ROOT_CA_FILE"
fi

API_BASE_URL="${SERVICE_API_URL:-${SERVICE_SERVER_URL:-https://localhost}}"

cat > "$MOBILE_ENV_FILE" <<EOF
# Auto-generated by scripts/run/run.mobile.dev.sh
EXPO_PUBLIC_API_URL=$API_BASE_URL
EXPO_PUBLIC_SSL_CERT_PATH=./certs/cert.pem
EXPO_PUBLIC_SSL_ROOT_CA_PATH=./certs/root-ca.pem
EOF

echo "[OK] Generated mobile env: $MOBILE_ENV_FILE"

if [[ -f "$TARGET_ROOT_CA_FILE" ]]; then
  export NODE_EXTRA_CA_CERTS="$TARGET_ROOT_CA_FILE"
  echo "[OK] NODE_EXTRA_CA_CERTS=$NODE_EXTRA_CA_CERTS"
fi

MODE="start"
DRY_RUN=0
for arg in "$@"; do
  case "$arg" in
    --android)
      MODE="android"
      ;;
    --ios)
      MODE="ios"
      ;;
    --start)
      MODE="start"
      ;;
    --dry-run)
      DRY_RUN=1
      ;;
    --help|-h)
      echo "Usage: bash scripts/run/run.mobile.dev.sh [--start|--android|--ios] [--dry-run]"
      exit 0
      ;;
    *)
      echo "[WARN] Unknown arg: $arg"
      ;;
  esac
done

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "[OK] Dry run selesai. Tidak menjalankan Expo command."
  exit 0
fi

cd "$WORKSPACE_DIR"

case "$MODE" in
  android)
    echo "[RUN] pnpm --filter mobile android"
    pnpm --filter mobile android
    ;;
  ios)
    echo "[RUN] pnpm --filter mobile ios"
    pnpm --filter mobile ios
    ;;
  *)
    echo "[RUN] pnpm --filter mobile start"
    pnpm --filter mobile start
    ;;
esac
