#!/bin/bash

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"

OUTPUT_FILE="$ROOT_DIR/infra/nginx/default.conf.vps.template"
SINGLE_MODE=0
SERVICE=""
DOMAIN=""
HOST_FILE_NAME=""
SSL_MODE="letsencrypt"
SSL_BASE_DIR="/etc/letsencrypt/live"
STEPCA_SSL_DIR="/etc/nginx/ssl"
SSL_CERT=""
SSL_KEY=""
FORCE_APPEND=0

ensure_output_is_file() {
  local target="$1"
  local normalized="${target%/}"

  if [ -z "$normalized" ]; then
    echo -e "${RED}[ERROR]${NC} Output path is invalid: '$target'"
    exit 1
  fi

  if [ -d "$normalized" ]; then
    if [ -n "$(ls -A "$normalized" 2>/dev/null)" ]; then
      echo -e "${RED}[ERROR]${NC} Output path is a non-empty directory: $normalized"
      echo -e "${YELLOW}[HINT]${NC} Remove or rename the directory, then run again."
      exit 1
    fi

    rmdir "$normalized"
    echo -e "${YELLOW}[FIX]${NC} Removed empty directory at output path: $normalized"
  fi

  mkdir -p "$(dirname "$normalized")"
  OUTPUT_FILE="$normalized"
}

usage() {
  cat <<USAGE
Usage: $0 --single --service=NAME --domain=DOMAIN [options]

Options:
  --single
  --service=NAME          app|pma|s3|s3-console|grafana|reverb|hmr
  --domain=DOMAIN         Hostname (can be URL, will be normalized)
  --host-file-name=NAME   Reference name saved to .env.devops (optional)
  --ssl-mode=MODE         letsencrypt|stepca|manual (default: letsencrypt)
  --ssl-cert=PATH         SSL cert path (required for --ssl-mode=manual)
  --ssl-key=PATH          SSL key path (required for --ssl-mode=manual)
  --ssl-base-dir=PATH     Base for letsencrypt certs (default: /etc/letsencrypt/live)
  --stepca-ssl-dir=PATH   Base for stepca certs (default: /etc/nginx/ssl)
  --output=PATH           Output host template file (default: infra/nginx/default.conf.vps.template)
  --force-append          Append even if same service/domain marker exists
  --help
USAGE
}

extract_host() {
  local host="$1"
  host="${host#http://}"
  host="${host#https://}"
  host="${host%%/*}"
  host="${host%%:*}"
  printf '%s\n' "$host"
}

load_env() {
  local f="$1"
  if [ -f "$f" ]; then
    set -a
    source "$f"
    set +a
  fi
}

upsert_env_reference() {
  local file="$1"
  local key="$2"
  local value="$3"
  [ -f "$file" ] || return 0

  if grep -qE "^${key}=" "$file"; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$file"
  else
    echo "${key}=${value}" >> "$file"
  fi
}

resolve_cert_key() {
  local domain="$1"
  local cert=""
  local key=""

  case "$SSL_MODE" in
    manual)
      [ -z "$SSL_CERT" ] && { echo -e "${RED}[ERROR]${NC} --ssl-cert required for manual mode"; exit 1; }
      [ -z "$SSL_KEY" ] && { echo -e "${RED}[ERROR]${NC} --ssl-key required for manual mode"; exit 1; }
      cert="$SSL_CERT"
      key="$SSL_KEY"
      ;;
    letsencrypt)
      cert="${SSL_CERT:-${SSL_BASE_DIR}/${domain}/fullchain.pem}"
      key="${SSL_KEY:-${SSL_BASE_DIR}/${domain}/privkey.pem}"
      ;;
    stepca)
      cert="${SSL_CERT:-${STEPCA_SSL_DIR}/${domain}.pem}"
      key="${SSL_KEY:-${STEPCA_SSL_DIR}/${domain}.key}"
      ;;
    *)
      echo -e "${RED}[ERROR]${NC} invalid --ssl-mode: $SSL_MODE"
      exit 1
      ;;
  esac

  echo "$cert|$key"
}

init_host_template_if_missing() {
  local file="$1"
  [ -f "$file" ] && return
  mkdir -p "$(dirname "$file")"
  cat > "$file" <<'EOF'
# Generated by setup-nginx-host-template.sh (single append mode)
# Deploy this file with scripts/setup/setup-nginx-host.sh
EOF
}

append_host_block() {
  local file="$1"
  local service="$2"
  local domain="$3"

  if [ "$FORCE_APPEND" -ne 1 ] && grep -q "GENERATED HOST ENTRY: ${service}:${domain}" "$file"; then
    echo -e "${YELLOW}[SKIP]${NC} Entry ${service}:${domain} already exists"
    return
  fi

  local cert_and_key cert key
  cert_and_key="$(resolve_cert_key "$domain")"
  cert="${cert_and_key%%|*}"
  key="${cert_and_key#*|}"

  local lb_port="${SERVICE_LOAD_BALANCER_PORT:-80}"
  local grafana_port="${GRAFANA_PORT:-3000}"

  {
    echo ""
    echo "# ========================================================="
    echo "# GENERATED HOST ENTRY: ${service}:${domain}"
    echo "# ========================================================="
    echo "server {"
    echo "    listen 443 ssl http2;"
    echo "    server_name ${domain};"
    echo ""
    echo "    ssl_certificate     ${cert};"
    echo "    ssl_certificate_key ${key};"
    echo ""
    echo "    access_log /var/log/nginx/app-boilerplate_${service}_access.log;"
    echo "    error_log  /var/log/nginx/app-boilerplate_${service}_error.log warn;"
    echo ""
    echo "    location / {"
    if [ "$service" = "grafana" ]; then
      echo "        proxy_pass http://127.0.0.1:${grafana_port};"
    else
      echo "        proxy_pass http://127.0.0.1:${lb_port};"
    fi
    cat <<'EOF'

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
EOF
  } >> "$file"

  echo -e "${GREEN}[OK]${NC} Appended host entry ${service}:${domain} into $file"
}

for arg in "$@"; do
  case "$arg" in
    --single) SINGLE_MODE=1 ;;
    --service=*) SERVICE="${arg#*=}" ;;
    --domain=*) DOMAIN="${arg#*=}" ;;
    --host-file-name=*) HOST_FILE_NAME="${arg#*=}" ;;
    --ssl-mode=*) SSL_MODE="${arg#*=}" ;;
    --ssl-cert=*) SSL_CERT="${arg#*=}" ;;
    --ssl-key=*) SSL_KEY="${arg#*=}" ;;
    --ssl-base-dir=*) SSL_BASE_DIR="${arg#*=}" ;;
    --stepca-ssl-dir=*) STEPCA_SSL_DIR="${arg#*=}" ;;
    --output=*) OUTPUT_FILE="${arg#*=}" ;;
    --force-append) FORCE_APPEND=1 ;;
    --help) usage; exit 0 ;;
    *) echo -e "${RED}[ERROR]${NC} Unknown argument: $arg"; usage; exit 1 ;;
  esac
done

load_env "$ROOT_DIR/.env"
load_env "$ROOT_DIR/.env.backend"
load_env "$ROOT_DIR/.env.devops"

ensure_output_is_file "$OUTPUT_FILE"

if [ "$SINGLE_MODE" -ne 1 ]; then
  echo -e "${RED}[ERROR]${NC} Only single mode is supported. Use --single"
  usage
  exit 1
fi

[ -z "$SERVICE" ] && { echo -e "${RED}[ERROR]${NC} --service is required"; exit 1; }

if [ -z "$DOMAIN" ]; then
  case "$SERVICE" in
    app) DOMAIN="${SERVICE_SERVER_DOMAIN:-}" ;;
    pma) DOMAIN="${SERVICE_PMA_DOMAIN:-${SERVICE_PMA_ABSOLUTE_URI:-${PHPMYADMIN_URL:-}}}" ;;
    s3) DOMAIN="${SERVICE_S3_DOMAIN:-${S3_URL:-}}" ;;
    s3-console) DOMAIN="${SERVICE_S3_CONSOLE_DOMAIN:-${S3_CONSOLE_URL:-}}" ;;
    grafana) DOMAIN="${GRAFANA_URL:-}" ;;
    reverb) DOMAIN="${SERVICE_REVERB_DOMAIN:-${SERVICE_REVERB_URL:-}}" ;;
    hmr) DOMAIN="${SERVICE_HMR_URL:-}" ;;
  esac
fi

DOMAIN="$(extract_host "$DOMAIN")"
[ -z "$DOMAIN" ] && { echo -e "${RED}[ERROR]${NC} Invalid/empty domain"; exit 1; }

case "$SERVICE" in
  app|pma|s3|s3-console|grafana|reverb|hmr) ;;
  *) echo -e "${RED}[ERROR]${NC} Unsupported service: $SERVICE"; exit 1 ;;
esac

init_host_template_if_missing "$OUTPUT_FILE"
append_host_block "$OUTPUT_FILE" "$SERVICE" "$DOMAIN"

HOST_FILE_NAME="${HOST_FILE_NAME:-${SERVICE_SERVER_DOMAIN:-$DOMAIN}}"
upsert_env_reference "$ROOT_DIR/.env.devops" "NGINX_HOST_FILE_NAME" "$HOST_FILE_NAME"
upsert_env_reference "$ROOT_DIR/.env.devops" "NGINX_SSL_MODE" "$SSL_MODE"
